-- 특정 형질을 가지는 대장균 찾기
-- 프로그래머스 (미등록 문제)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/301646
-- 작성자: 서윤범
-- 작성일: 2026. 06. 15. 12:01:52

# # SELECT COUNT(*) AS COUNT FROM (SELECT RIGHT(BIN(GENOTYPE), 4) AS GENOTYPE FROM ECOLI_DATA) A
# # WHERE SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-2,1) = '0'
# # AND (SUBSTRING(LPAD(A.GENOTYPE,4,'0'), -1,1) = '1' OR SUBSTRING(LPAD(A.GENOTYPE,4,'0'), -3,1) = '1')

# SELECT COUNT(*) AS COUNT FROM (SELECT RIGHT(BIN(GENOTYPE),4) AS GENOTYPE FROM ECOLI_DATA) AS A
# WHERE SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-2,1) = '0'
# AND (SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-1,1) = '1'
#      OR SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-3,1) = '1')


SELECT COUNT(*) AS COUNT FROM (SELECT RIGHT(BIN(GENOTYPE),4) AS GENOTYPE FROM ECOLI_DATA) AS A
WHERE SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-2,1) = '0'
AND (SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-3,1) = '1'
     OR SUBSTRING(LPAD(A.GENOTYPE,4,'0'),-1,1) = '1')








