-- 식품분류별 가장 비싼 식품의 정보 조회하기
-- 프로그래머스 중급 (⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131116
-- 작성자: 서윤범
-- 작성일: 2026. 04. 10. 17:20:31

# 서브쿼리
# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT AS A
# WHERE CATEGORY IN ('과자','국','김치','식용유')
# AND PRICE = (
#     SELECT MAX(PRICE)
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY = A.CATEGORY
# )
# ORDER BY MAX_PRICE DESC




# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자','국','김치','식용유')
# AND (CATEGORY, PRICE) IN (
#     SELECT CATEGORY, MAX(PRICE)
#     FROM FOOD_PRODUCT
#     GROUP BY CATEGORY
# )
# ORDER BY MAX_PRICE DESC





SELECT CATEGORY, PRICE, PRODUCT_NAME FROM FOOD_PRODUCT AS A
WHERE CATEGORY IN ('식용유','과자','국','김치')
AND PRICE = (
    SELECT MAX(PRICE) FROM FOOD_PRODUCT AS B
    WHERE A.CATEGORY = B.CATEGORY
)
ORDER BY PRICE DESC

# SELECT * FROM FOOD_PRODUCT
# ORDER BY PRICE DESC




