-- 없어진 기록 찾기
-- 프로그래머스 중급 (⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/59042
-- 작성자: 서윤범
-- 작성일: 2026. 04. 10. 17:50:58

# SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS AS O
# LEFT JOIN ANIMAL_INS AS I
# ON O.ANIMAL_ID = I.ANIMAL_ID
# WHERE I.ANIMAL_ID IS NULL









SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS AS O
LEFT JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID