-- 오프라인/온라인 판매 데이터 통합하기
-- 프로그래머스 중급 (⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131537
-- 작성자: 서윤범
-- 작성일: 2026. 08. 08. 15:27:34

WITH CTE AS (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03')
SELECT * FROM CTE
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID