-- 조건에 부합하는 중고거래 댓글 조회하기
-- 프로그래머스 기초 (⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/164673
-- 작성자: 서윤범
-- 작성일: 2026. 06. 16. 11:07:30

# SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, 
# DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD AS B
# JOIN USED_GOODS_REPLY AS R
# ON B.BOARD_ID = R.BOARD_ID
# WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
# ORDER BY CREATED_DATE, B.TITLE


SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, R.CREATED_DATE FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE, B.TITLE






